name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: install dependencies
        run: |
          cd doc
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: build
        run: |
          cd doc
          make html

      - name: deploy docs
        run: |
          mv doc/build/html /tmp/
          touch /tmp/html/.nojekyll

      - name: deploy configuration
        run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.MY_REPO }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: push
        env:
          GITHUB_USER: "autobuilder"
          GITHUB_EMAIL: "densuke+autobuild@st.kobedenshi.ac.jp"
        run: |
          git checkout gh-pages
          git rm -fr .
          cp -vr /tmp/html/ ./
          git config --local user.name "${GITHUB_USER}"
          git config --local user.email "${GITHUB_EMAIL}"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git add .
          git commit -m "auto rebuilding site"
          git push origin gh-pages
